# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoitem', '0002_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(default='medium', max_length=6),
        ),
    ]
